- name: command vs shell
  hosts:  local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.command: ls -ltr

  - name: execute the command and keep output
    ansible.builtin.command: ls -ltr > /tmp/output.txt